"""
PM Tool - Document Generator & Exporter
Generates professional Product Requirement Documents (PRDs), Roadmaps, and Technical Specs in DOCX and Markdown formats.
"""

from io import BytesIO
from typing import Optional, Dict, Any, List
import re


def generate_docx_from_markdown(title: str, markdown_content: str, metadata: Optional[Dict[str, str]] = None) -> BytesIO:
    """
    Converts markdown text into a professionally styled DOCX document in-memory.
    """
    import docx
    from docx.shared import Inches, Pt, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.enum.table import WD_TABLE_ALIGNMENT
    from docx.oxml import OxmlElement
    from docx.oxml.ns import qn

    doc = docx.Document()

    # Configure 1-inch margins
    sections = doc.sections
    for section in sections:
        section.top_margin = Inches(1.0)
        section.bottom_margin = Inches(1.0)
        section.left_margin = Inches(1.0)
        section.right_margin = Inches(1.0)

    # Document Header Title
    title_p = doc.add_paragraph()
    title_p.paragraph_format.space_before = Pt(12)
    title_p.paragraph_format.space_after = Pt(6)
    title_p.paragraph_format.alignment = WD_ALIGN_PARAGRAPH.LEFT
    title_run = title_p.add_run(title or "Product Requirement Document")
    title_run.font.size = Pt(24)
    title_run.font.bold = True
    title_run.font.color.rgb = RGBColor(0x1A, 0x1A, 0x1A)

    # Sub-caption / Tagline
    sub_p = doc.add_paragraph()
    sub_p.paragraph_format.space_after = Pt(16)
    sub_run = sub_p.add_run("Generated by PM Tool Enterprise Copilot")
    sub_run.font.size = Pt(10)
    sub_run.font.italic = True
    sub_run.font.color.rgb = RGBColor(0x7A, 0x58, 0x20)

    # Metadata Table (if provided)
    meta = metadata or {}
    if meta:
        table = doc.add_table(rows=0, cols=2)
        table.alignment = WD_TABLE_ALIGNMENT.LEFT
        table.autofit = False

        for k, v in meta.items():
            row_cells = table.add_row().cells
            row_cells[0].width = Inches(2.0)
            row_cells[1].width = Inches(4.5)

            p_key = row_cells[0].paragraphs[0]
            k_run = p_key.add_run(str(k))
            k_run.font.bold = True
            k_run.font.size = Pt(9.5)
            k_run.font.color.rgb = RGBColor(0x44, 0x44, 0x44)

            p_val = row_cells[1].paragraphs[0]
            v_run = p_val.add_run(str(v))
            v_run.font.size = Pt(9.5)
            v_run.font.color.rgb = RGBColor(0x22, 0x22, 0x22)

        # Spacing after table
        sp = doc.add_paragraph()
        sp.paragraph_format.space_after = Pt(14)

    # Parse and add markdown lines
    lines = markdown_content.splitlines()
    in_code_block = False
    code_lines: List[str] = []

    for line in lines:
        stripped = line.strip()

        # Handle Code Fences
        if stripped.startswith("```"):
            if in_code_block:
                # Close code block
                in_code_block = False
                p = doc.add_paragraph()
                p.paragraph_format.space_before = Pt(4)
                p.paragraph_format.space_after = Pt(8)
                p.paragraph_format.left_indent = Inches(0.25)
                run = p.add_run("\n".join(code_lines))
                run.font.name = "Consolas"
                run.font.size = Pt(9)
                run.font.color.rgb = RGBColor(0x2A, 0x2A, 0x2A)
                code_lines = []
            else:
                in_code_block = True
                code_lines = []
            continue

        if in_code_block:
            code_lines.append(line)
            continue

        if not stripped:
            continue

        # Header 1
        if stripped.startswith("# "):
            h_text = stripped[2:].strip()
            h = doc.add_heading(level=1)
            h.paragraph_format.space_before = Pt(14)
            h.paragraph_format.space_after = Pt(4)
            r = h.add_run(h_text)
            r.font.size = Pt(16)
            r.font.bold = True
            r.font.color.rgb = RGBColor(0x11, 0x11, 0x11)
            continue

        # Header 2
        if stripped.startswith("## "):
            h_text = stripped[3:].strip()
            h = doc.add_heading(level=2)
            h.paragraph_format.space_before = Pt(12)
            h.paragraph_format.space_after = Pt(3)
            r = h.add_run(h_text)
            r.font.size = Pt(13)
            r.font.bold = True
            r.font.color.rgb = RGBColor(0x33, 0x33, 0x33)
            continue

        # Header 3
        if stripped.startswith("### "):
            h_text = stripped[4:].strip()
            h = doc.add_heading(level=3)
            h.paragraph_format.space_before = Pt(10)
            h.paragraph_format.space_after = Pt(2)
            r = h.add_run(h_text)
            r.font.size = Pt(11)
            r.font.bold = True
            r.font.color.rgb = RGBColor(0x55, 0x55, 0x55)
            continue

        # Bullet list item
        if stripped.startswith("- ") or stripped.startswith("* "):
            bullet_text = stripped[2:].strip()
            p = doc.add_paragraph(style="List Bullet")
            p.paragraph_format.space_before = Pt(1)
            p.paragraph_format.space_after = Pt(2)
            _render_inline_formatting(p, bullet_text)
            continue

        # Numbered list item
        num_match = re.match(r"^(\d+)\.\s+(.*)$", stripped)
        if num_match:
            item_text = num_match.group(2)
            p = doc.add_paragraph(style="List Number")
            p.paragraph_format.space_before = Pt(1)
            p.paragraph_format.space_after = Pt(2)
            _render_inline_formatting(p, item_text)
            continue

        # Blockquote
        if stripped.startswith("> "):
            quote_text = stripped[2:].strip()
            p = doc.add_paragraph()
            p.paragraph_format.left_indent = Inches(0.3)
            p.paragraph_format.space_before = Pt(4)
            p.paragraph_format.space_after = Pt(4)
            run = p.add_run(f"“{quote_text}”")
            run.font.italic = True
            run.font.color.rgb = RGBColor(0x55, 0x55, 0x55)
            continue

        # Standard paragraph
        p = doc.add_paragraph()
        p.paragraph_format.space_before = Pt(2)
        p.paragraph_format.space_after = Pt(6)
        p.paragraph_format.line_spacing = 1.15
        _render_inline_formatting(p, stripped)

    buffer = BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer


def _render_inline_formatting(paragraph, text: str):
    """Parses bold (**text**), italics (*text*), and inline code (`code`) into runs."""
    import docx
    from docx.shared import Pt, RGBColor

    # Pattern matches **bold**, *italic*, `code`, or plain text chunks
    tokens = re.split(r"(\*\*[^*]+\*\*|\*[^*]+\*|`[^`]+`)", text)
    for token in tokens:
        if not token:
            continue
        if token.startswith("**") and token.endswith("**") and len(token) > 4:
            run = paragraph.add_run(token[2:-2])
            run.font.bold = True
        elif token.startswith("*") and token.endswith("*") and len(token) > 2:
            run = paragraph.add_run(token[1:-1])
            run.font.italic = True
        elif token.startswith("`") and token.endswith("`") and len(token) > 2:
            run = paragraph.add_run(token[1:-1])
            run.font.name = "Consolas"
            run.font.size = Pt(9.5)
            run.font.color.rgb = RGBColor(0x8A, 0x3B, 0x14)
        else:
            run = paragraph.add_run(token)
            run.font.size = Pt(10.5)
